### ISSUE TITLE
`fq.gz` files throw errors

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/demo#6]
### Description of the bug

Need to remove “.fq.gz” from docs.

Files not picked up by seqtk.

### Command used and terminal output

```console
nextflow run nf-core/demo -profile singularity --input samplesheet.csv
```

### Relevant files

fq.gz don't work :(

**Comment by christopher-hakkaart** [comment]
Need to remove reference to `fq.gz` files in reference docs as they are not detected by `seqtk_trim` process

**Comment by maxulysse** [comment]
issue with seqtk_trim?
Does the tool need fastq.gz?

**Comment by christopher-hakkaart** [comment]
Ahhh - now I look at it again maybe not... There was a weird error but now I think about it again it might not be weird

**Comment by christopher-hakkaart** [comment]
I'm pretty sure it's the input taking any file type (e.g., `fq.gz`) and the output expecting `fastq.gz`. So the module can be updated to be more flexible.

**Comment by maxulysse** [comment]
Ping me on the PR

**Comment by christopher-hakkaart** [comment]
Fixed
